openapi: 3.0.0
info:
  title: HNG Openapi Nodejs Docs
  version: 1.0.0
  description: Api Documentation for nodejs boilerplate
servers:
  - url: http://localhost:5000
paths:
  /api/v1/users:
    post:
      summary: create a new user account
      security:
        - bearerAuth: []
      requestBody:
        content:
         application/json:
          schema:
           $ref: '#/components/schemas/User'
      responses:
        "201":
          description: registration successful
        '400':
          description: Bad request
        '500':
          description: Internal server error
    get:
      summary: get all users account
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful operation
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /api/v1/auth/register:
    post:
      summary: User creates their account
      requestBody:
        content:
         application/json:
          schema:
           $ref: '#/components/schemas/User'
      responses:
        "201":
          description: Account registration successful
        '400':
          description: Bad request
  /api/v1/auth/login:  
    post:
      summary: login a user
      requestBody:
        content:
         application/json:
          schema:
           $ref: '#/components/schemas/User'
      responses:
        "200":
          description: login successful
        "400": 
          description: Bad request
  /api/v1/user/:userId:
    get:
      summary: Get a single user account
      security:
        - bearerAuth: []
      params: userId
      responses:
        "200":
          description: Account retrieved successfully
        "404":
          description: Account not found
    patch:
      summary: Update user account
      security:
        - bearerAuth: []
      params: userId
      requestBody:
        content:
          schema:
            $ref: '#/components/schemas/User'
      responses:
        "200":
          description: Account updated successfully
        "404":
          description: Account with supplied ID not found
    delete:
      summary: delete a single user account
      security:
        - bearerAuth: []
      params: userId
      responses:
        "200":
          description: Account deleted successfully
        "404":
          description: Account not found
  /api/v1/organisation:
    post:
      summary: Create an organisation
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ''
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

        
